[package]
name = "chip8-engine"
version = "0.1.0"
authors = ["Dr. ERDI Gergo <gergo@erdi.hu>"]

[dependencies]
core = { git = "https://github.com/gergoerdi/rust-avr-libcore-mini", rev = "84829bbcb215a0dabd195b7f0610e37b43ef7038" }
