[package]
name = "chip8-engine"
version = "0.1.0"
authors = ["Dr. ERDI Gergo <gergo@erdi.hu>"]

[dependencies]
libcore-mini = { git = "https://github.com/gergoerdi/rust-avr-libcore-mini", tag = "v0.1.0" }
